version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: techteam
      MYSQL_PASSWORD: 123456Aa@
      MYSQL_ROOT_HOST: "%"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - rabbitmq_go_net
  swordhaelth:
    container_name: swordhaelth
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: "yarn start"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    links:
      - rabbitmq
      - db
    depends_on:
      - rabbitmq
      - db

networks:
  rabbitmq_go_net:
    driver: bridge
